language: node_js
node_js: '14.9'
dist: xenial
before_script:
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.6.0/z3-4.6.0-x64-ubuntu-16.04.zip -O /tmp/z3-4.6.0-x64-ubuntu-16.04.zip
  - unzip -d . /tmp/z3-4.6.0-x64-ubuntu-16.04.zip
  - export PATH=$PATH:$PWD/z3-4.6.0-x64-ubuntu-16.04/bin/
  - npm prune
  - npm install
script:
  - commitlint-travis
  - npm run lint
  - npm test
  - npm run build
after_success:
  - npx semantic-release
